# workflow triggers

# To test invoking this trigger, you need to send a special POST request to the following URL:
# https://api.github.com/repos/{owner}/{repo}/dispatches
#
# The request also needs to contain the following headers:
#
# "Accept": "application/vnd.github+json"
# "Authorization": "token {personal token with repo access}"
#
# You need to provide a personal GitHub token with the repo access scope.
# If your trigger also features a type, specify it in the request body:
#
# {"event_type": "webhook"}

name: Test Bitbucket webhook

on:
    push:
      branches: [ source ]
    pull_request:
      branches: [ source ]
    workflow_dispatch:
      inputs:
        unit:
          required: false
        integration:
          required: false
        payload:
          required: false
          # type: string

        # logLevel:
        #   description: 'Log level'
        #   required: true
        #   default: 'warning'
        #   type: choice
        #   options:
        #   - info
        #   - warning
        #   - debug
        # tags:
        #   description: 'Test scenario tags'
        #   required: false
        #   type: boolean
        # environment:
        #   description: 'Environment to run tests against'
        #   type: environment
        #   required: true
  
    # Allows external webhook trigger
    repository_dispatch:
      types:
        - webhook

jobs:
    debug:
        name: Debug GitHub workflow
        runs-on: ubuntu-latest

        steps:
        - run: |
            echo "DEBUG: id=$(id)"
            echo "DEBUG: hostname=$(hostname)"
            echo "DEBUG: Print process environment"
            printenv | sort
            echo "DEBUG: Print workflow context"
            echo "DEBUG:   unit: $UNIT"
            echo "DEBUG:   integration: $INTEGRATION"
            echo "DEBUG:   payload: $PAYLOAD"
          env:
            UNIT: "${{ inputs.unit }}"
            INTEGRATION: "${{ inputs.integration }}"
            PAYLOAD: "${{ inputs.payload }}"
            
# EOF